### ISSUE TITLE
Microsoft Edge Issue

### ISSUE THREAD

**Issue by ZeroDawn0D** [kewbish/kewbish.github.io#1]
Browser: Microsoft Edge 44.18362.449.0

<img width="947" alt="edgerror0" src="https://user-images.githubusercontent.com/54509868/80142016-1f1a6b80-85c8-11ea-83b8-293b2acb1929.png">

After selecting the text:
<img width="948" alt="edgerror" src="https://user-images.githubusercontent.com/54509868/80142063-322d3b80-85c8-11ea-9f78-bd8f86727662.png">

**Comment by kewbish** [comment]
This apparently has to do with the incompatibility of `linear-gradient`, thanks for noticing.
