### ISSUE TITLE
Earl Or Justin

### ISSUE THREAD

**Issue by RainbowsInTheDark** [kewbish/kewbish.github.io#2]
We all need to know ho you favor kewbish

**Comment by kewbish** [comment]
I don't favour hoes you idiot.

**Comment by RainbowsInTheDark** [comment]
Thats dumb you like Justin ur password that quizlet is JSTN

**Comment by kewbish** [comment]
Wait how the f do you know that

**Comment by RainbowsInTheDark** [comment]
I know a lot of things. You aren't the only person with the skills needed
to find some  secrets.

**Comment by kewbish** [comment]
Oh shit, Rylan's getting real
